<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */

$helper = $this->helper('Magento\Search\Helper\Data');
$configProvider = $block->getData('configProvider');
?>
<?php 
	$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 
	$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
	$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
	$categories = $categoryHelper->getStoreCategories();

?>
<div class="search-form select-search">
        <form class="form minisearch form-inline" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
			<div class="form-search d-flex align-items-center">
				<div class="header-search-block d-flex align-items-center">
						<input id="search"
						<?php if ($configProvider->isSuggestionsAllowed()):?>
							data-mage-init='{"quickSearch":{
									"formSelector":"#search_mini_form",
									"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
									"destinationSelector":"#search_autocomplete"}
							}'
						<?php endif;?>
						type="text"
						name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
						value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
						placeholder="<?php /* @escapeNotVerified */ echo __('Enter Keyword to Search...'); ?>"
						class="input-text form-control"
						maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
						role="combobox"
						aria-expanded="true"
						aria-haspopup="false"
						aria-autocomplete="both"
						autocomplete="off"/>
					<?php /* Custom search by category */ ?>
					
					<?php $currentCategory = ""; ?>
					<?php $currentCategoryId = ""; ?>
					
					<input type="hidden" name="cat" id="cat" value="<?php echo $currentCategoryId; ?>"/>
					<div class="search-select">
						<span id="cat-active-name" onclick="toggleCatSearch()" class="search-cat-active">
							<?php if($currentCategory != ""): ?>
								<?php echo $currentCategory ?>
							<?php else: ?>
								<?php echo __('All Categories'); ?>
							<?php endif ?>
						</span>
						<ul id="select-cat-dropdown" style="display:none;">
							<li>
								<span onclick="setSearchCatValue('', '<?php echo __('All Categories') ?>')"><?php echo __('All Categories') ?></span>
							</li>
							<?php
								foreach ($categories as $category) {
									
									?>
									<li class="level">
										<span onclick="setSearchCatValue('<?php echo $category->getId() ;?>', '<?php echo $category->getName() ;?>')"><?php echo $category->getName() ;?></span>
									</li>
									<?php

									
								}
							?>
						</ul>
					</div>
				</div>
				<div class="actions d-flex align-self-stretch">
					<button type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>" class="action search align-self-stretch">
						<span><?= $block->escapeHtml(__('Search')) ?></span>
					</button>
				</div>
			</div>
        </form>
    </div>

<script type="text/javascript">
function setSearchCatValue(id,name){
	require([
	'jquery'
	], function(jQuery){
		(function($) {
			$('#cat').val(id);
			$('#cat-active-name').html(name);
			$('#select-cat-dropdown').hide();
		})(jQuery);
	});
}
function toggleCatSearch(){
	require([
	'jquery'
	], function(jQuery){
		(function($) {
			$('#select-cat-dropdown').slideToggle();
		})(jQuery);
	});
}
</script>