<?php
    $categories = $this->getCategoryCollection();
    $categoryHelper = $this->getCategoryHelper();
?>
<div class="widget block block-static-block" id="catewithimg">
    <div class="block-content">
        <div class="section-heading">
            <h2 class="title"><?php echo $this->getMainTitle(); ?></h2>
        </div>
        <div class="category-list-block">
            <div class="owl-carousel">
                <?php
                foreach($categories as $category):
                    $cat = $this->getCategorymodel($category->getId());
                    $image = $cat->getImageUrl();
                ?>
                    <?php if($image != null): ?>
                        <div class="cat-slider-block">
                            <a class="category_name" href="<?php echo $cat->getUrl(); ?>">
                                <span class="cat-thumb d-flex align-items-center">
                                    <img src="<?php echo $image; ?>" class="img-responsive category_image" alt="<?php echo $cat->getName(); ?>" />
                                </span>
                                <span class="cat_name"><?php echo $cat->getName(); ?></span>
                            </a>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
<script>
    require([
        'jquery',
        'owlcarousel'
        ], function () {
            'use strict';
            jQuery.noConflict();
                jQuery(".category-list-block .owl-carousel").owlCarousel({
                    nav: true, // Show next and prev buttons
                    navText:["<",">"], //show prev next
                    loop: false,
                    autoplay: false, //Set AutoPlay  
                    margin: 30,
                    items : 5,
                    dots: false,
                    responsive:{
                        0:{
                            items:1,
                            nav:true,
                            dots: false,
                        },
                        600:{
                            items:3,
                            dots: false,
                            nav:true
                        },
                        1000:{
                            items:5,
                            dots: false,
                            nav:true,
                            
                        }
                    }
          });
    });
</script>