<?php
$class = $block->getType();
$image = 'most_sold_products_list';
$items = $block->getItems();
$showAddTo = true;
$showCart  = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$newProduct = $block->getProductCollection();
?>

    
    <div class="product data items home-product-tabs"
     data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 0}}'>

        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#tab-newproducts">New Products</a>
        </div>
        <div id="tab-newproducts" class="item content" data-role="content">
            <?php echo $this->getLayout()->createBlock("Magento\Catalog\Block\Product\Widget\NewWidget")->setDisplayType("all_products")->setProductsCount("5")->setTemplate("product/widget/new/content/new_grid.phtml")->toHtml(); ?>

        </div>

        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#tab-toprating">Top Rating</a>
        </div>
        <div id="tab-toprating" class="item content" data-role="content">
            <?php echo $this->getLayout()->createBlock("Magento\Catalog\Block\Product\Widget\NewWidget")->setDisplayType("all_products")->setProductsCount("5")->setTemplate("product/widget/new/content/new_grid.phtml")->toHtml(); ?>
        </div>

        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#block-<?php /* @escapeNotVerified */ echo $class ?>-heading">
                <?php /* @escapeNotVerified */ echo $block->getTitle() ?>
            </a>
        </div>
        <div id="block-<?php /* @escapeNotVerified */ echo $class ?>-heading" class="item content" data-role="content">

            <?php if ($block->getItems()->getSize()): ?>
            <!-- Most Selling Content -->
            <div class="block <?php /* @escapeNotVerified */ echo $class ?>">
    
                <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class ?>-heading">
                    <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $class ?>">
                        <ol class="products list items product-items">
                            <?php $iterator = 1 ?>
                            <?php foreach ($items as $_item): ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>                
                            <div class="product-item-info">
                                <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                        <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>
                                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item) ?>
                                        <?php if ($templateType): ?>
                                            <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                        <?php endif ?>

                                        <?php if ($showAddTo || $showCart): ?>
                                            <div class="product actions product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <button class="action tocart primary"
                                                                        data-post='<?php /* @escapeNotVerified */ echo $postData ?>'
                                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php endif ?>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                            <?php endif ?>
                                                        <?php endif ?>
                                                    </div>
                                                <?php endif ?>

                                                <?php if ($showAddTo): ?>
                                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                            <?php echo $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                        <?php endif ?>
                                                    </div>
                                                <?php endif ?>
                                            </div>
                                        <?php endif ?>
                                    </div>
                                </div>
                                <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </ol>
                    </div>
                </div>
            </div>
            <?php endif ?>
        </div>
    
    </div>





